/*
 * Copyright 2015-2025 Ritense BV, the Netherlands.
 *
 * Licensed under EUPL, Version 1.2 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {PluginSpecification} from '@valtimo/plugin';
import {ROTTERDAM_ORACLE_EBS_PLUGIN_LOGO_BASE64} from './assets';
import {ConfigurationComponent} from "./components/configuration/configuration.component";
import {JournaalpostOpvoerenComponent} from "./components/journaalpost-opvoeren/journaalpost-opvoeren.component";
import {VerkoopfactuurOpvoerenComponent} from "./components/verkoopfactuur-opvoeren/verkoopfactuur-opvoeren.component";

const rotterdamOracleEbsPluginSpecification: PluginSpecification = {
    pluginId: 'rotterdam-oracle-ebs',
    pluginConfigurationComponent: ConfigurationComponent,
    pluginLogoBase64: ROTTERDAM_ORACLE_EBS_PLUGIN_LOGO_BASE64,
    functionConfigurationComponents: {
        'journaalpost-opvoeren': JournaalpostOpvoerenComponent,
        'verkoopfactuur-opvoeren': VerkoopfactuurOpvoerenComponent,
    },
    pluginTranslations: {
        nl: {
            title: 'Gemeente Rotterdam: Oracle E-Business Suite koppeling',
            description: 'Oracle E-Business Suite plugin voor o.a. het Opvoeren van een Journaalpost',
            'journaalpost-opvoeren': 'Journaalpost opvoeren',
            'verkoopfactuur-opvoeren': 'Verkoopfactuur opvoeren',
            'configuration.title': 'Configuratienaam',
            'configuration.title.tooltip': 'De naam van de huidige plugin-configuratie. Onder deze naam kan de configuratie in de rest van de applicatie teruggevonden worden.',
            'configuration.title.placeholder': 'Gemeente Rotterdam Oracle EBS Plugin',
            'configuration.baseUrl': 'ESB Url',
            'configuration.baseUrl.tooltip': 'De URL van de Gemeente Rotterdam (Opentunnel) ESB',
            'configuration.authenticationEnabled': 'Schakel Client Certificate Authenticatie (mTLS) in',
            'configuration.authenticationEnabled.yes': 'Ja',
            'configuration.authenticationEnabled.no': 'Nee',
            'configuration.certificateConfigurationInfo': 'Na opslaan wordt onderstaande informatie niet meer getoond bij opnieuw openen van het configuratie formulier.',
            'configuration.serverCertificate': 'Server certificaat',
            'configuration.serverCertificate.tooltip': 'Het certificaat in Base64 formaat',
            'configuration.clientCertificate': 'Client certificaat',
            'configuration.clientCertificate.tooltip': 'Het certificaat in Base64 formaat',
            'configuration.clientPrivateKey': 'Private key',
            'configuration.clientPrivateKey.tooltip': 'De private key in Base64 formaat',
            'journaalpost.procesCode': 'Proces code',
            'journaalpost.procesCode.tooltip': '',
            'journaalpost.referentieNummer': 'Referentienummer',
            'journaalpost.referentieNummer.tooltip': '',
            'journaalpost.sleutel': 'Sleutel',
            'journaalpost.sleutel.tooltip': '',
            'journaalpost.boekdatumTijd': 'Boekdatum',
            'journaalpost.boekdatumTijd.tooltip': '',
            'journaalpost.categorie': 'Categorie',
            'journaalpost.categorie.tooltip': '',
            'journaalpost.saldoSoort': 'Saldosoort',
            'journaalpost.saldoSoort.tooltip': '',
            'journaalpost.saldoSoort.placeholder': 'Maak een keuze',
            'journaalpost.omschrijving': 'Omschrijving',
            'journaalpost.omschrijving.tooltip': '',
            'journaalpost.boekjaar': 'Boekjaar',
            'journaalpost.boekjaar.tooltip': '',
            'journaalpost.boekperiode': 'Boekperiode',
            'journaalpost.boekperiode.tooltip': '',
            'journaalpost.regels': 'Regels',
            'journaalpost.regels.tooltip': '',
            'journaalpost.regel.toevoegen': 'Regel toevoegen',
            'journaalpost.regel.verwijderen': 'Regel verwijderen',
            'journaalpost.regel.grootboekSleutel': 'Grootboek sleutel',
            'journaalpost.regel.boekingType': 'Boekingtype',
            'journaalpost.regel.boekingType.placeholder': 'Maak een keuze',
            'journaalpost.regel.omschrijving': 'Omschrijving',
            'journaalpost.regel.bedrag': 'Bedrag',
            'verkoopfactuur.procesCode': 'Proces code',
            'verkoopfactuur.procesCode.tooltip': '',
            'verkoopfactuur.referentieNummer': 'Referentienummer',
            'verkoopfactuur.referentieNummer.tooltip': '',
            'verkoopfactuur.factuurKlasse': 'Factuur klasse',
            'verkoopfactuur.factuurKlasse.tooltip': '',
            'verkoopfactuur.factuurKlassePlaceholder': 'Maak een keuze',
            'verkoopfactuur.inkoopOrderReferentie': 'Inkoop Order Referentie',
            'verkoopfactuur.inkoopOrderReferentie.tooltip': '',
            'verkoopfactuur.natuurlijkPersoonAchternaam': 'Achternaam',
            'verkoopfactuur.natuurlijkPersoonAchternaam.tooltip': '',
            'verkoopfactuur.natuurlijkPersoonVoornamen': 'Voornamen',
            'verkoopfactuur.natuurlijkPersoonVoornamen.tooltip': '',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam': 'Statutaire naam',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam.tooltip': '',
            'verkoopfactuur.regels': 'Regels',
            'verkoopfactuur.regels.tooltip': '',
            'verkoopfactuur.regel.toevoegen': 'Regel toevoegen',
            'verkoopfactuur.regel.verwijderen': 'Regel verwijderen',
            'verkoopfactuur.regel.hoeveelheid': 'Hoeveelheid',
            'verkoopfactuur.regel.tarief': 'Tarief',
            'verkoopfactuur.regel.btwPercentage': 'BTW pPercentage',
            'verkoopfactuur.regel.grootboekSleutel': 'Grootboek sleutel',
            'verkoopfactuur.regel.omschrijving': 'Omschrijving',
        },
        en: {
            'journaalpost-opvoeren': 'Enter journal entry',
            'verkoopfactuur-opvoeren': 'Enter sales invoice',
            title: 'Municipality of Rotterdam: Oracle E-Business Suite connection',
            description: 'Oracle E-Business Suite plugin for, among other things, entering a journal entry',
            configurationTitle: 'Configuration name',
            configurationTitleTooltip: 'The name of the current plugin configuration. Under this name, the configuration can be found in the rest of the application.',
            baseUrl: 'ESB Url',
            baseUrlTooltip: 'The URL of the Municipality of Rotterdam (Opentunnel) ESB',
            authenticationEnabled: 'Enable Client Certificate Authenticatie (mTLS)',
            yes: 'Yes',
            no: 'No',
            certificateConfigurationInfo: 'After saving, the information below will no longer be shown when reopening the configuration form.',
            serverCertificate: 'Server certificate',
            serverCertificateTooltip: 'The certificate in Base64 format',
            clientCertificate: 'Client certificate',
            clientCertificateTooltip: 'The certifcate in Base64 format',
            clientPrivateKey: 'Private key',
            clientPrivateKeyTooltip: 'The private key in Base64 format',
            regelToevoegen: 'Add line',
            regelVerwijderen: 'Remove line',
            procesCode: 'Process code',
            procesCodeTooltip: '',
            referentieNummer: 'Reference number',
            referentieNummerTooltip: '',
            sleutel: 'Key',
            sleutelTooltip: '',
            boekdatum: 'Booking date',
            boekdatumTooltip: '',
            categorie: 'Category',
            categorieTooltip: '',
            saldoSoort: 'Balance type',
            saldoSoortTooltip: '',
            saldoSoortPlaceholder: 'Make a choice',
            omschrijving: 'Description',
            omschrijvingTooltip: '',
            boekjaar: 'Financial year',
            boekjaarTooltip: '',
            boekperiode: 'Accounting period',
            boekperiodeTooltip: '',
            grootboekSleutel: 'General ledger key',
            boekingType: 'Booking type',
            boekingTypePlaceholder: 'Make a choice',
            regelOmschrijving: 'Description',
            bedrag: 'Amount',
            journaalpostRegels: 'Lines',
            journaalpostRegelsTooltip: '',
            verkoopfactuurRegels: 'Lines',
            verkoopfactuurRegelsTooltip: '',
        },
        de: {
            'journaalpost-opvoeren': 'Journalbuchung erfassen',
            'verkoopfactuur-opvoeren': 'Verkaufsrechnung erfassen',
            title: 'Gemeinde Rotterdam: Oracle E-Business Suite-Anbindung',
            description: 'Oracle E-Business Suite Plugin, u.a. zur Erfassung eines Journaleintrags',
            configurationTitle: 'Konfigurationsname',
            configurationTitleTooltip: 'Der Name der aktuellen Plugin-Konfiguration. Unter diesem Namen ist die Konfiguration im weiteren Verlauf der Anwendung zu finden.',
            baseUrl: 'ESB Url',
            baseUrlTooltip: 'De URL van de Gemeinde Rotterdam (Opentunnel) ESB',
            authenticationEnabled: 'Client-Zertifikatauthentifizierung (mTLS) aktivieren',
            yes: 'Ja',
            no: 'Nein',
            certificateConfigurationInfo: 'Nach dem Speichern werden die untenstehenden Informationen beim erneuten Öffnen des Konfigurationsformulars nicht mehr angezeigt.',
            serverCertificate: 'Serverzertifikat',
            serverCertificateTooltip: 'Zertifikat im Base64-Format',
            clientCertificate: 'Client-Zertifikat',
            clientCertificateTooltip: 'Zertifikat im Base64-Format',
            clientPrivateKey: 'Privater Schlüssel',
            clientPrivateKeyTooltip: 'Privater Schlüssel im Base64-Format',
            regelToevoegen: 'Regel hinzufügen',
            regelVerwijderen: 'Regel entfernen',
            procesCode: 'Prozesscode',
            procesCodeTooltip: '',
            referentieNummer: 'Referenznummer',
            referentieNummerTooltip: '',
            sleutel: 'Schlüssel',
            sleutelTooltip: '',
            boekdatum: 'Buchungsdatum',
            boekdatumTooltip: '',
            categorie: 'Kategorie',
            categorieTooltip: '',
            saldoSoort: 'Saldoart',
            saldoSoortTooltip: '',
            saldoSoortPlaceholder: 'Bitte wählen',
            omschrijving: 'Beschreibung',
            omschrijvingTooltip: '',
            boekjaar: 'Buchungsjahr',
            boekjaarTooltip: '',
            boekperiode: 'Buchungsperiode',
            boekperiodeTooltip: '',
            grootboekSleutel: 'Hauptbuchschlüssel',
            boekingType: 'Buchungstyp',
            boekingTypePlaceholder: 'Bitte wählen',
            regelOmschrijving: 'Beschreibung',
            bedrag: 'Betrag',
            journaalpostRegels: 'Regeln',
            journaalpostRegelsTooltip: '',
            verkoopfactuurRegels: 'Regeln',
            verkoopfactuurRegelsTooltip: '',
        },
    },
};

export {rotterdamOracleEbsPluginSpecification};
