version: "3.9"
services:

  brp-example-core-db:
    container_name: brp-example-core-db
    image: postgres:14.1
    ports:
      - "54340:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brp-example-core-db

  brp-example-core-keycloak:
    container_name: brp-example-core-keycloak
    depends_on:
      - brp-example-core-keycloak-db
    image: quay.io/keycloak/keycloak:17.0.1-legacy
    volumes:
      - ./docker/imports/keycloak:/opt/jboss/keycloak/imports
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: brp-example-core-keycloak-db
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/opt/jboss/keycloak/imports/realm.json"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"

  brp-example-core-keycloak-db:
    image: postgres:14.1
    container_name: brp-example-core-keycloak-db
    ports:
      - "54329:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-keycloak}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-keycloak}
